[package]
name = "advent_of_code_22_day_5"
version = "0.1.0"
authors = ["tijoer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
num-derive = "0.3.3"